main: "jp.nagua.npractice.Main"
name: "nPractice"
version: "${project.version}"
api-version: 1.8
author: MovingEmoji
commands:
  ping:
    description: Show player ping
    usage: /ping
  location:
    description: Save location to data
    usage: /location [LocationName]
    permission: nprac.location
  inventory:
    description: Save common inventory set
    usage: /inventory [load/save/delete] [InventoryName]
    permission: nprac.inventory
  rename:
    description: Change your held item name
    usage: /rename [Text]
    permission: nprac.rename
  kit:
    description: Create or Edit kit
    usage: /kit [create/delete/list] [Text] [Text]
    permission: nprac.kit
  arena:
    description: Create or edit arena
    usage: /arena [create/delete/list] [Text] [Text]
    permission: nprac.arena
  trigger:
    description: Set function trigger item
    usage: /trigger [Text]
    permission: nprac.trigger