main: "jp.nagua.nGame.Main"
name: "nGame"
version: "1.0"
api-version: 1.8
author: MovingEmoji
commands:
  ping:
    description: Show player ping
    usage: /ping
  location:
    description: Save location to data
    usage: /location [LocationName]
  inventory:
    description: Save common inventory set
    usage: /inventory [load/save/delete] [InventoryName]
